# Generated by Django 5.0.1 on 2024-01-31 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bobur', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Bobur.post'),
        ),
    ]
